name: mobile_pgb
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  badges: ^3.1.2
  bloc: ^9.0.0
  build_runner: ^2.4.14
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  cart_stepper: ^4.3.0
  cunning_document_scanner: ^1.2.3
  cupertino_icons: ^1.0.8
  custom_rating_bar: ^3.0.0
  detectable_text_field: ^3.0.2
  equatable: ^2.0.7
  extended_image: ^9.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_html: ^3.0.0
  flutter_native_splash: ^2.4.4
  flutter_spinkit: ^5.2.1
  gallery_saver_plus: ^3.2.4
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  get_it: ^8.0.3
  go_router: ^15.1.1
  go_router_builder: ^2.9.0
  google_maps_flutter: ^2.12.2
  http: ^1.4.0
  hydrated_bloc: ^10.0.0
  image_cropper: ^9.1.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  json_annotation: ^4.9.0
  json_serializable: ^6.9.3
  multi_image_picker_plus: ^0.0.7
  path_provider: ^2.1.5
  photo_manager: ^3.7.0
  photo_view: ^0.15.0
  pinput: ^2.2.3
  pull_to_refresh: ^2.0.0
  shimmer: ^3.0.0
  slide_countdown: ^2.0.2
  slide_to_confirm: ^1.1.0
  socket_io_client: ^3.1.2
  table_calendar: ^3.2.0
  url_launcher: ^6.3.1
  webview_flutter: ^4.11.0
  permission_handler: ^11.4.0
  flutter_contacts: ^1.1.9+2
  timeago: ^3.7.1
  chewie: ^1.11.3
  visibility_detector: ^0.4.0+2
  video_player: ^2.9.5
  open_file_plus: ^3.4.1+1
  sn_progress_dialog: ^1.2.0
  flutter_image_compress: ^2.4.0
  file_picker: ^10.1.9
  video_compress_v2: ^1.0.0+1
  filesize: ^2.0.1
  flutter_mentions: ^2.0.1
  barcode_widget: ^2.0.4
  syncfusion_flutter_calendar: ^29.1.38

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-ExtraBold.ttf
        - asset: assets/fonts/Inter-Medium.ttf

flutter_native_splash:
  color: "#062565"
  image: assets/images/logo_transparant.png
  android: true
  ios: true
  fullscreen: true
